stages:
  - test
  - build

cache:
  paths:
    - backend/.m2/repository
    - frontend/node_modules

# -------------------------
# Backend: run Maven tests
# -------------------------
backend-test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - cd backend
    - mvn -B test
  artifacts:
    when: always
    reports:
      junit: backend/target/surefire-reports/*.xml

# -------------------------
# Frontend: lint + unit tests
# -------------------------
frontend-test:
  stage: test
  image: node:22-alpine
  script:
    - cd frontend
    - npm ci
    - npm run lint
    - npm test     
  artifacts:
    when: always


# -------------------------
# Frontend: build
# -------------------------
frontend-build:
  stage: build
  image: node:22-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist
