spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3307/aspd_db
spring.datasource.username=aspd_user
spring.datasource.password=aspd_team3
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.org.springframework.security=DEBUG