spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3307/aspd_db
spring.datasource.username=aspd_user
spring.datasource.password=aspd_team3
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.org.springframework.security=DEBUG
spring.jackson.serialization.fail-on-empty-beans=false
spring.sql.init.mode=never


#I Used them for debugging, maybe helpful to fix bugs in the future :
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE
#logging.level.org.springframework.web=DEBUG
#server.error.include-stacktrace=always
#server.error.include-message=always
#logging.level.com.aspd.backend= DEBUG

